export const data = [
  { id: 1, name: "GeekforGeeks 1" },
  { id: 2, name: "GeekforGeeks 2" },
  { id: 3, name: "GeekforGeeks 3" },
  { id: 4, name: "GeekforGeeks 4" },
  { id: 5, name: "GeekforGeeks 5" },
  { id: 6, name: "GeekforGeeks 6" },
  { id: 7, name: "GeekforGeeks 7" },
  { id: 8, name: "GeekforGeeks 8" },
  { id: 9, name: "GeekforGeeks 9" },
  { id: 10, name: "GeekforGeeks 10" },
  { id: 11, name: "GeekforGeeks 11" },
  { id: 12, name: "GeekforGeeks 12" },
  { id: 13, name: "GeekforGeeks 13" },
  { id: 14, name: "GeekforGeeks 14" },
  { id: 15, name: "GeekforGeeks 15" },
  { id: 16, name: "GeekforGeeks 16" },
  { id: 17, name: "GeekforGeeks 17" },
  { id: 18, name: "GeekforGeeks 18" },
  { id: 19, name: "GeekforGeeks 19" },
  { id: 20, name: "GeekforGeeks 20" },
];
